name = "Official"
description = "This is the official repo for [Gradience](https://github.com/GradienceTeam/Gradience)."
maintainer = "GradienceTeam"
url = "https://usegradience.github.io"
repo = "https://github.com/gradiencepresets/official"
support = "https://github.com/gradiencepresets/official/issue" # or matrix ?

base_url = "https://raw.githubusercontent.com/gradiencepresets/official.{name}/main/{name}.toml"

presets = [ "adwaita"]

additional = """## New preset process

Presets can be moved from the `curated` status to the [`official`](/official) status. That's the process:

1. The preset should already be in this org. If not, refer to the [new](https://github.com/gradience-presets/new) repo.
2. Open an issue and select the `New preset` template.
3. After opening the preset, the preset will be in review. For being accepted, the preset must be voted by at least 50% of the team."""

contributing = """Report issues and contribute to the project on [GitHub](https://github.com/GradienceTeam/Gradience)."""
