name = "Incubator"
description = "This is a repo for testing new presets [Gradience](https://github.com/GradienceTeam/Gradience)."
maintainer = "GradienceTeam"
url = "https://usegradience.github.io"
repo = "https://github.com/gradiencepresets/incubator"
support = "https://github.com/gradiencepresets/incubator/issue" # or matrix ?

base_url = "https://raw.githubusercontent.com/gradiencepresets/incubator.{name}/main/{name}.toml"

presets = []

additional = """"""
contributing = """Report issues and contribute to the project on [GitHub](https://github.com/GradienceTeam/Gradience)."""
