try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib

import tomli_w
import requests

with open("config.toml", "rb") as f:
    config = tomllib.load(f)
print(f"Generating `{config['name']}.toml` ...")

base_url = config["base_url"]

presets_list = config["presets"]

generated = {
    "name": config["name"],
    "url": config["url"],
    "support": config["support"],
    "repo": config["repo"],
    "maintainer": config["maintainer"]
}
print("The following presets will be added to the repo:")
presets = {}
for preset in presets_list:
    name = preset
    raw_url = base_url.format(name=preset)
    try:
        r = requests.get(raw_url, timeout=5)
        r.raise_for_status()
    except requests.exceptions.HTTPError as e:
        print(f"  x {name}: {e}")
    else:
        online_preset = tomllib.loads(r.text)
        preset = {
            "raw": raw_url,
            "badges": online_preset["badges"],
            "description": online_preset["description"]
        }

        presets[name] = preset
        print("  -", name)

generated["presets"] = presets

gen = tomli_w.dumps(generated)

print("Writing to file ...")
with open("official.toml", "w", encoding="utf-8") as f:
    f.write("# This file was generated by ./generate.py\n")
    f.write("# Do not edit this file manually, your changes will be overwritten\n")
    f.write("# Instead, edit config.toml and run ./generate.py\n")
    f.write("# Or push to the repo and wait for the GitHub Action to run\n")
    f.write("\n")

    f.write(gen)

    print("Done!")
